version: '3.3'
services:
  backend:
    env_file:
      - env-couchbase.env
      - env-sync-gateway.env
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
  celeryworker:
    env_file:
      - env-couchbase.env
      - env-sync-gateway.env
      - env-backend.env
  sync-gateway:
    env_file:
      - env-couchbase.env
      - env-sync-gateway.env
